os: linux
dist: trusty
language: python
python: 2.7

branches:
  except:
    - gh-pages

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/Library/Caches/pip
    - $TRAVIS_BUILD_DIR/cache/wheel

addons:
  #srcclr:
  #  debug: true
  apt:
    packages:
    - libgmp3-dev
    - build-essential
    - git
    - libssl-dev
    - libffi-dev

before_install:
  - virtualenv venv
  - source venv/bin/activate

install:
  - pip install -U pip==9.0.3
  - pip install -r requirements.txt
  - pip install -r requirements_testing.txt
  - pip install .

script:
  - pip install mock pylint
  - pylint lbrynet
  - PYTHONPATH=. trial lbrynet.tests
  - rvm install ruby-2.3.1
  - rvm use 2.3.1 && gem install danger --version '~> 4.0' && danger
