dist: xenial
sudo: true
language: python
python: "3.7"

jobs:
  include:

    - stage: code quality
      name: "pylint & mypy"
      install:
        - pip install git+https://github.com/PyCQA/pylint.git
        - pip install mypy
        - pip install -e .
      script:
        - pylint --rcfile=setup.cfg torba
        - mypy torba
    after_success: skip

    - &unit-tests
      stage: unit tests
      install:
        - pip install tox-travis
      script: TESTTYPE=unit tox
    - <<: *unit-tests
      python: "3.6"

    - &integration-tests
      stage: integration tests
      install:
        - pip install tox-travis
        - pushd .. && git clone https://github.com/lbryio/electrumx.git --branch lbryumx && popd
        - pushd .. && git clone https://github.com/lbryio/orchstr8.git && popd
      script: TESTTYPE=integration tox

after_success:
  - pip install coverage
  - coverage combine tests/
  - bash <(curl -s https://codecov.io/bash)
