language: python

python:
  - "2.7"
  - "3.6"

install:
  - pip install tox-travis coverage
  - pushd .. && git clone https://github.com/lbryio/electrumx.git --branch packages && popd
  - pushd .. && git clone https://github.com/lbryio/orchstr8.git --branch wip && popd

script: tox

after_success:
  - coverage combine tests/
  - bash <(curl -s https://codecov.io/bash)
