language: python

python:
  - "3.7"

install:
  - pip install tox-travis coverage
  - pushd .. && git clone https://github.com/lbryio/electrumx.git --branch lbryumx && popd
  - pushd .. && git clone https://github.com/lbryio/orchstr8.git && popd

script: tox

after_success:
  - coverage combine tests/
  - bash <(curl -s https://codecov.io/bash)
