version: 1.0.{build}

init:
- ps: $env:Path += ";C:\MinGW\bin\"
- ps: gcc --version
- ps: mingw32-make --version
- ps: mkdir C:\temp
- ps: Invoke-WebRequest "https://pypi.python.org/packages/55/90/e987e28ed29b571f315afea7d317b6bf4a551e37386b344190cffec60e72/miniupnpc-1.9.tar.gz" -OutFile "C:\temp\miniupnpc-1.9.tar.gz"
- ps: cd C:\temp
- ps: 7z e miniupnpc-1.9.tar.gz
- ps: 7z x miniupnpc-1.9.tar
- ps: cd C:\temp\miniupnpc-1.9
- ps: |
        mingw32-make.exe -f Makefile.mingw
        C:\Python27\python.exe C:\temp\miniupnpc-1.9\setupmingw32.py build --compiler=mingw32
        C:\Python27\python.exe C:\temp\miniupnpc-1.9\setupmingw32.py install
- ps: Invoke-WebRequest "https://github.com/lbryio/lbry/raw/master/packaging/windows/libs/gmpy-1.17-cp27-none-win32.whl" -OutFile "C:\temp\gmpy-1.17-cp27-none-win32.whl"
- ps: C:\Python27\Scripts\pip.exe install "C:\temp\gmpy-1.17-cp27-none-win32.whl"
- ps: C:\Python27\Scripts\pip.exe install pypiwin32==219
- ps: C:\Python27\Scripts\pip.exe install six==1.9.0
- ps: C:\Python27\Scripts\pip.exe install requests==2.9.1
- ps: C:\Python27\Scripts\pip.exe install zope.interface==4.1.3
- ps: C:\Python27\Scripts\pip.exe install cx-freeze==4.3.3
- ps: C:\Python27\Scripts\pip.exe install cython==0.24.1
- ps: C:\Python27\Scripts\pip.exe install Twisted==16.0.0
- ps: C:\Python27\Scripts\pip.exe install Yapsy==1.11.223
- ps: C:\Python27\Scripts\pip.exe install appdirs==1.4.0
- ps: C:\Python27\Scripts\pip.exe install argparse==1.2.1
- ps: C:\Python27\Scripts\pip.exe install colorama==0.3.7
- ps: C:\Python27\Scripts\pip.exe install dnspython==1.12.0
- ps: C:\Python27\Scripts\pip.exe install ecdsa==0.13
- ps: C:\Python27\Scripts\pip.exe install jsonrpc==1.2
- ps: C:\Python27\Scripts\pip.exe install jsonrpclib==0.1.7
- ps: C:\Python27\Scripts\pip.exe install loggly-python-handler==1.0.0
- ps: C:\Python27\Scripts\pip.exe install pbkdf2==1.3
- ps: C:\Python27\Scripts\pip.exe install protobuf==3.0.0
- ps: C:\Python27\Scripts\pip.exe install pycrypto==2.6.1
- ps: C:\Python27\Scripts\pip.exe install python-bitcoinrpc==0.1
- ps: C:\Python27\Scripts\pip.exe install qrcode==5.2.2
- ps: C:\Python27\Scripts\pip.exe install requests_futures==0.9.7
- ps: C:\Python27\Scripts\pip.exe install seccure==0.3.1.3
- ps: C:\Python27\Scripts\pip.exe install simplejson==3.8.2
- ps: C:\Python27\Scripts\pip.exe install slowaes==0.1a1
- ps: C:\Python27\Scripts\pip.exe install txJSON-RPC==0.3.1
- ps: C:\Python27\Scripts\pip.exe install unqlite==0.5.3
- ps: C:\Python27\Scripts\pip.exe install wsgiref==0.1.2
- ps: C:\Python27\Scripts\pip.exe install base58==0.2.2
- ps: C:\Python27\Scripts\pip.exe install googlefinance==0.7
- ps: C:\Python27\Scripts\pip.exe install git+https://github.com/lbryio/lbryum.git
- ps: cd C:\temp
- ps: Invoke-WebRequest "https://github.com/lbryio/lbry/archive/v0.4.0.tar.gz" -OutFile "C:\temp\lbrynet-v0-4-0.tar.gz"
- ps: 7z e lbrynet-v0-4-0.tar.gz
- ps: 7z x lbrynet-v0-4-0.tar
- ps: cd C:\temp\lbrynet-v0-4-0

build_script:
- cmd: C:\Python27\python.exe setup_win32.py build bdist_msi

artifacts:
- path: dist/*.msi
  name: msi
- path: build/exe.win32-2.7/
  name: lbry-portable
- path: packaging/windows/lbry-win32-app/LBRY-URI.reg
  name: LBRY-URI